export {default as Landing} from './layout/Landing';
export {default as Navbar} from './layout/Navbar';
export {default as Login} from './auth/Login';
export {default as Register} from './auth/Register';
export {default as CustomerProfile} from './CustomerProfile/CustomerProfile';
export {default as EditProfile} from './CustomerProfile/EditProfile/EditProfile';
export {default as CreateProfile} from './CustomerProfile/CreateProfile/CreateProfile';
export {default as Home} from './home/home'
export {default as Products} from './products/products'
export {default as About} from './about/about'
export {default as Contact} from './contact/contact'
export {default as Footer} from './footer/footer'
export {default as ProductDetails} from './products/product-details/product_detail';
export {default as Cart} from './cart/cart';